### ISSUE TITLE
clear the selection after setState

### ISSUE THREAD

**Issue by alessandronocera89** [Arif-un/react-multiple-select-dropdown-lite#6]
Hi, just a simple question:
I've developed a component that allow my app to POST data retrieved by this dropdown selection.
One simple "save button" allow me to call my api and store the data then the `setState` is invoked to re-render the page (to show the new things) but inside the dropdown selection still remains the previous one value.
There is a way to "remove" this value from the dropdown view after the save?
<img width="217" alt="Screenshot 2021-04-22 at 17 58 28" src="https://user-images.githubusercontent.com/56973508/115746171-66cb0300-a394-11eb-8271-a599fb2036ed.png">
I want to be able to see the dropdown "cleared" after `setState`, without do an hard page refresh. It's possible?

Thank you!

**Comment by Arif-un** [comment]
Hi @alessandronocera89 ,
You can set the "defaultValue" prop to empty string or empty array it will update the dropdown value.
Thanks

**Comment by Chiragjot** [comment]
> Hi @alessandronocera89 , You can set the "defaultValue" prop to empty string or empty array it will update the dropdown value. Thanks

Is there a way to do it without setState and by using useState.

**Comment by Arif-un** [comment]
I don't think so, how do you plan to do it ? @Chiragjot
